seleniumhub:
    image: selenium/hub
    ports:
      - 4444:4444
  
  # chromednode:
  #   image: selenium/node-chrome-debug:2.53.0
  #   expose:
  #     - 5900
  #   links:
  #     - seleniumhub:hub
  
  # firefoxnode:
  #   image: selenium/node-firefox
  #   expose:
  #     - 5900
  #   links:
  #     - seleniumhub:hub
  
  chromenode:
    image: selenium/node-chrome
    ports:
      - 5900
    links:
      - seleniumhub:hub
      
      #To run scripts with nodes
      #docker-compose up -d
      #docker-compose scale chromenode=5
      #docker-compose scale firefox=5
